/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Dao.FlightDao;
import Dao.Flight_PassengerDao;
import Dao.Imple.FlightDaoImple;
import Dao.Imple.Flight_PassengerDaoImple;
import Dao.Imple.PassengerDaoImple;
import Dao.PassengerDao;
import Model.Flight;
import Model.Flight_Passenger;
import Model.Item;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vusal
 */
public class TicketStatistics extends javax.swing.JFrame {

    /**
     * Creates new form TicketStatistics
     */
    Flight_PassengerDao flight_PassengerDao = null;
    FlightDao flightDao = null;
    PassengerDao passengerDao = null;

    public TicketStatistics() {
        initComponents();
        flight_PassengerDao = new Flight_PassengerDaoImple();
        flightDao = new FlightDaoImple();
        passengerDao = new PassengerDaoImple();
        FlightCombo();
        try {
            showFlight_PassengerList(flight_PassengerDao.getFlightPassengerList());
        } catch (Exception ex) {
            Logger.getLogger(TicketStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GlobTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Counter = new javax.swing.JLabel();
        FlightCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("        Tciket Statistics");

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GlobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(GlobTable);

        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Counter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Counter.setText("Flight Count :");

        FlightCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Flight" }));

        jLabel2.setText("Select Flight");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FlightCombo, 0, 133, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(Counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(Counter)
                    .addComponent(FlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Model.Flight_Passenger flight_Passenger = new Flight_Passenger();
        Model.Flight flight = new Flight();
        Item flightItem = (Item) FlightCombo.getSelectedItem();
        flight.setId(flightItem.getId());
        flight_Passenger.setFlight(flight);
        try {
            List<Flight_Passenger> flight_Passengers = flight_PassengerDao.searchAdvancedFlight_Passengers(flight_Passenger);
            showFlight_PassengerList(flight_Passengers);
            Counter.setText("Ticket Count : " + flight_Passengers.size());
        } catch (Exception ex) {
            Logger.getLogger(TicketStatistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketStatistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Counter;
    private javax.swing.JComboBox FlightCombo;
    private javax.swing.JTable GlobTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
  private void FlightCombo() {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) FlightCombo.getModel();
            List<Flight> flights = flightDao.getFlightList();
            for (Flight flight : flights) {
                model.addElement(new Item(flight.getId(), String.valueOf(flight.getFlight_code())));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showFlight_PassengerList(List<Model.Flight_Passenger> listFlight_Passenger) {

        try {

            DefaultTableModel model = new DefaultTableModel();
            GlobTable.setModel(model);
            model.addColumn("Id");
            model.addColumn("Flight_No");
            model.addColumn("Passenger Full Name");
            model.addColumn("Passenger Passport");
            model.addColumn("Departure Airport");
            model.addColumn("Arrival_airport");
            model.addColumn("Departure Date");
            model.addColumn("Arrival Date");
            model.addColumn("Company");
            model.addColumn("Plane");

            for (Model.Flight_Passenger flight_Passenger : listFlight_Passenger) {
                Object[] data = new Object[]{
                    flight_Passenger.getId(), flight_Passenger.getFlight().getFlight_code(), flight_Passenger.getPassenger().getName() + " " + flight_Passenger.getPassenger().getSurname(), flight_Passenger.getPassenger().getPassportId(),
                    flight_Passenger.getFlight().getDeparture_airport().getName(), flight_Passenger.getFlight().getArrival_airport().getName(),
                    flight_Passenger.getFlight().getDeparture_date(), flight_Passenger.getFlight().getArrival_date(),
                    flight_Passenger.getFlight().getCompany().getCompany_name(), flight_Passenger.getFlight().getPlane().getName(),};
                model.addRow(data);
            }
            /*for (int i = 0; i <= 4; i++) {
             for (int j = 0; j <= 4; j++) {
             isCellEditable(i, j);
             }
             }*/
            GlobTable.getColumnModel().getColumn(0).setMinWidth(0);
            GlobTable.setEnabled(true);
            GlobTable.getColumnModel().getColumn(0).setMaxWidth(0);
            GlobTable.getColumnModel().getColumn(0).setWidth(0);
            model.fireTableDataChanged();
        } catch (Exception e) {

        }
    }
}
