/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Update;

import Dao.AirportDao;
import Dao.CompanyDao;
import Dao.FlightDao;
import Dao.Imple.AirportDaoImple;
import Dao.Imple.CompanyDaoImple;
import Dao.Imple.FlightDaoImple;
import Dao.Imple.PlaneDaoImple;
import Dao.PlaneDao;
import Model.Airport;
import Model.Company;
import Model.Flight;
import Model.Item;
import Model.Plane;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vusal
 */
public class UpdateFlight extends javax.swing.JFrame {

    /**
     * Creates new form AddFlight
     */
    FlightDao flightDao = null;
    AirportDao airportDao = null;
    PlaneDao planeDao = null;
    CompanyDao companyDao = null;
    long selectedId = 0;

    public UpdateFlight() {
        initComponents();
        flightDao = new FlightDaoImple();
        airportDao = new AirportDaoImple();
        planeDao = new PlaneDaoImple();
        companyDao = new CompanyDaoImple();

        DepAirportCombo();
        ArrAirportCombo();
        PlaneCombo();
        CompanyCombo();
    }

    public UpdateFlight(long selectedId) {
        initComponents();
        flightDao = new FlightDaoImple();
        airportDao = new AirportDaoImple();
        planeDao = new PlaneDaoImple();
        companyDao = new CompanyDaoImple();
        this.selectedId = selectedId;
        System.out.println("Id : " + selectedId);
        DepAirportCombo();
        ArrAirportCombo();
        PlaneCombo();
        CompanyCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FlightNoTxt = new javax.swing.JTextField();
        DepAirportCombo = new javax.swing.JComboBox();
        ArrAirportCombo = new javax.swing.JComboBox();
        PlaneCombo = new javax.swing.JComboBox();
        DepDate = new com.toedter.calendar.JDateChooser();
        ArrDate = new com.toedter.calendar.JDateChooser();
        ClearBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CompanyCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Nimbus"); // NOI18N
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("       Update Flight");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Flight No");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Arrival Airport");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Departure Airport");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Plane");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Arrival Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Departure Date");

        FlightNoTxt.setText("jTextField2");

        DepAirportCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Departure Airport" }));

        ArrAirportCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Arrival Airport" }));

        PlaneCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Plane" }));

        ClearBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClearBtnMousePressed(evt);
            }
        });

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Company");

        CompanyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Company" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FlightNoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DepAirportCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArrAirportCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlaneCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(CompanyCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DepDate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrDate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FlightNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepAirportCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrAirportCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlaneCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CompanyCombo)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClearBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBtnMousePressed
        // TODO add your handling code here:

        FlightNoTxt.setText(null);
        DepAirportCombo.setSelectedIndex(0);
        ArrAirportCombo.setSelectedIndex(0);
        PlaneCombo.setSelectedIndex(0);
        DepDate.setDate(null);
        ArrDate.setDate(null);
    }//GEN-LAST:event_ClearBtnMousePressed

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
        // TODO add your handling code here:
        try {
            Flight flight = new Flight();
            Airport depAirport = new Airport();
            Airport arrAirport = new Airport();
            Plane plane = new Plane();
            Company company = new Company();
            Item depAirportItem = (Item) DepAirportCombo.getSelectedItem();
            Item arrAirportItem = (Item) ArrAirportCombo.getSelectedItem();
            Item planeItem = (Item) PlaneCombo.getSelectedItem();
            Item companyİtem = (Item) CompanyCombo.getSelectedItem();
            flight.setId(selectedId);
            flight.setFlight_code(Long.parseLong(FlightNoTxt.getText()));
            depAirport.setId(depAirportItem.getId());
            arrAirport.setId(arrAirportItem.getId());
            flight.setDeparture_airport(depAirport);
            flight.setArrival_airport(arrAirport);
            company.setId(companyİtem.getId());
            flight.setCompany(company);
            plane.setId(planeItem.getId());
            flight.setPlane(plane);
            java.util.Date depd = DepDate.getDate();
            java.sql.Date depsqldate = new java.sql.Date(depd.getTime());
            flight.setDeparture_date(depsqldate);
            java.util.Date arrd = ArrDate.getDate();
            java.sql.Date arrsqldate = new java.sql.Date(arrd.getTime());
            flight.setArrival_date(arrsqldate);
            //flight.setArrival_date(  ArrDate.getDate());
            flight.setActive(1);

            boolean isAdded = flightDao.updateFlight(flight);
            if (isAdded) {
                JOptionPane.showMessageDialog(null, "Flight has been added", "Add Flight", HEIGHT);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Error", "Add Flight", HEIGHT);
            }
        } catch (Exception ex) {
            Logger.getLogger(UpdateFlight.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }


    }//GEN-LAST:event_SaveBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ArrAirportCombo;
    private com.toedter.calendar.JDateChooser ArrDate;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JComboBox CompanyCombo;
    private javax.swing.JComboBox DepAirportCombo;
    private com.toedter.calendar.JDateChooser DepDate;
    private javax.swing.JTextField FlightNoTxt;
    private javax.swing.JComboBox PlaneCombo;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 private void DepAirportCombo() {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) DepAirportCombo.getModel();
            Flight selectedFlight = flightDao.getFlightById(selectedId);
            List<Airport> airports = airportDao.getAirportList();
            for (Airport airport : airports) {
                model.addElement(new Item(airport.getId(), airport.getName()));
            }
            model.setSelectedItem(new Item(selectedFlight.getDeparture_airport().getId(), selectedFlight.getDeparture_airport().getName()));
            FlightNoTxt.setText(String.valueOf(selectedFlight.getFlight_code()));
            DepDate.setDate(selectedFlight.getDeparture_date());
            ArrDate.setDate(selectedFlight.getArrival_date());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void ArrAirportCombo() {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) ArrAirportCombo.getModel();
            Flight selectedFlight = flightDao.getFlightById(selectedId);
            List<Airport> airports = airportDao.getAirportList();
            for (Airport airport : airports) {
                model.addElement(new Item(airport.getId(), airport.getName()));
            }
            model.setSelectedItem(new Item(selectedFlight.getArrival_airport().getId(), selectedFlight.getArrival_airport().getName()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void PlaneCombo() {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) PlaneCombo.getModel();
            Flight selectedFlight = flightDao.getFlightById(selectedId);
            List<Plane> planes = planeDao.getPlaneList();
            for (Plane plane : planes) {
                model.addElement(new Item(plane.getId(), plane.getName()));
            }
            model.setSelectedItem(new Item(selectedFlight.getPlane().getId(), selectedFlight.getPlane().getName()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void CompanyCombo() {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) CompanyCombo.getModel();
            Flight selectedFlight = flightDao.getFlightById(selectedId);
            List<Company> companys = companyDao.getCompanyList();
            for (Company company : companys) {
                model.addElement(new Item(company.getId(), company.getCompany_name()));
            }
            model.setSelectedItem(new Item(selectedFlight.getCompany().getId(), selectedFlight.getCompany().getCompany_name()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

//    private void setFlightById(Long id) {
//        try {
//            Flight flight = flightDao.getFlightById(id);
//            FlightNoTxt.setText(String.valueOf(flight.getFlight_code()));
//            DefaultComboBoxModel model = (DefaultComboBoxModel) DepAirportCombo.getModel();
//            for (int i = 1; i < model.getSize(); i++) {
//               
//                if (flight.getDeparture_airport().getId() == ((Item) model.get).getId()) {
//                    DepAirportCombo.setSelectedIndex(i);
//                    System.out.println("Check : "+ DepAirportCombo.getItemAt(i));
//                }
//            };
//            DepAirportCombo.setSelectedIndex(WIDTH);
//        } catch (Exception ex) {
//            Logger.getLogger(UpdateFlight.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
}
